### ISSUE TITLE
Sample code ???

### ISSUE THREAD

**Issue by Andreotti100** [Carbon225/esp32-perfmon#1]
How to use?

**Comment by Carbon225** [comment]
https://github.com/Carbon225/esp32-perfmon#usage

Assuming you know how to install IDF components, just call ```perfmon_start()``` once anywhere in your code.
It will begin printing usage statistics to the serial console.

It's not accurate though, just some estimate.

**Comment by Andreotti100** [comment]
No, I don't know anything about IDF components.
I hoped it would work in the PlatformIO Arduino environment for the ESP32,
No problem about the accuracy, I just wanted to get an indication.

**Comment by Carbon225** [comment]
Sorry, I don't know if Platformio can use raw IDF components.
Since the code is just one file, you could copy-paste it into your code and see if it compiles.
If not, try adding the #includes and if that doesn't work then Platformio doesn't expose IDF headers (and that would be the end).

Since you're using Arduino, are you sure you are actually using RTOS features?
If you're not using any blocking functions (like sleep, not delay!) then the CPU would be at 100% anyway.

**Comment by Andreotti100** [comment]
The PlatformIO Arduino framework is build on RTOS if I am not mistaken. Underlying functions can be called also.
Don't bother, I will figure it out, you pointed me in a direction I can explore further.
Thanks buddy!
